window.SCREENER = [
  {
    "date": "2026-09-22",
    "runAt": "2026-09-22 18:45",
    "count": 17,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "002129",
        "name": "TCL中环",
        "industry": "光伏设备",
        "price": 9.61,
        "gain": 6.54,
        "turnover": 5.42,
        "volRatio": 3.85,
        "cap": 389,
        "yang": 3,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "603978",
        "name": "深圳新星",
        "industry": "金属新材料",
        "price": 26.2,
        "gain": 6.16,
        "turnover": 12.33,
        "volRatio": 1.4,
        "cap": 55,
        "yang": 7,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "002338",
        "name": "奥普光电",
        "industry": "军工电子Ⅱ",
        "price": 45.15,
        "gain": 5.99,
        "turnover": 3.77,
        "volRatio": 2.43,
        "cap": 108,
        "yang": 3,
        "aboveRate": 95,
        "sector": ""
      },
      {
        "code": "600605",
        "name": "汇通能源",
        "industry": "一般零售",
        "price": 28.74,
        "gain": 5.66,
        "turnover": 4.67,
        "volRatio": 2.35,
        "cap": 59,
        "yang": 5,
        "aboveRate": 98,
        "sector": "消费"
      },
      {
        "code": "600792",
        "name": "云煤能源",
        "industry": "焦炭Ⅱ",
        "price": 5.75,
        "gain": 5.31,
        "turnover": 16.53,
        "volRatio": 1.12,
        "cap": 64,
        "yang": 4,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "603073",
        "name": "彩蝶实业",
        "industry": "化学纤维",
        "price": 17.36,
        "gain": 5.21,
        "turnover": 2.84,
        "volRatio": 1.75,
        "cap": 20,
        "yang": 5,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "600121",
        "name": "郑州煤电",
        "industry": "煤炭开采",
        "price": 5.27,
        "gain": 5.19,
        "turnover": 16.73,
        "volRatio": 1.35,
        "cap": 64,
        "yang": 5,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "003033",
        "name": "征和工业",
        "industry": "摩托车及其他",
        "price": 89.3,
        "gain": 4.74,
        "turnover": 4.94,
        "volRatio": 1.44,
        "cap": 73,
        "yang": 5,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "001368",
        "name": "通达创智",
        "industry": "文娱用品",
        "price": 34.84,
        "gain": 4.62,
        "turnover": 5.12,
        "volRatio": 1.14,
        "cap": 39,
        "yang": 5,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "600828",
        "name": "茂业商业",
        "industry": "一般零售",
        "price": 4.62,
        "gain": 4.52,
        "turnover": 2.79,
        "volRatio": 1.33,
        "cap": 80,
        "yang": 5,
        "aboveRate": 95,
        "sector": "消费"
      },
      {
        "code": "000002",
        "name": "万  科Ａ",
        "industry": "房地产开发",
        "price": 3.81,
        "gain": 4.38,
        "turnover": 8.44,
        "volRatio": 2.8,
        "cap": 455,
        "yang": 5,
        "aboveRate": 95,
        "sector": "地产"
      },
      {
        "code": "603105",
        "name": "芯能科技",
        "industry": "电力",
        "price": 8.53,
        "gain": 4.28,
        "turnover": 7.63,
        "volRatio": 1.34,
        "cap": 43,
        "yang": 3,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "002333",
        "name": "罗普斯金",
        "industry": "装修建材",
        "price": 5.62,
        "gain": 4.27,
        "turnover": 2.94,
        "volRatio": 2.3,
        "cap": 38,
        "yang": 2,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "600610",
        "name": "中毅达",
        "industry": "化学原料",
        "price": 8.11,
        "gain": 4.24,
        "turnover": 7.25,
        "volRatio": 2.12,
        "cap": 87,
        "yang": 4,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "603271",
        "name": "永杰新材",
        "industry": "工业金属",
        "price": 40.38,
        "gain": 3.86,
        "turnover": 2.88,
        "volRatio": 2.42,
        "cap": 80,
        "yang": 3,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "002253",
        "name": "川大智胜",
        "industry": "软件开发",
        "price": 10.27,
        "gain": 3.63,
        "turnover": 4.23,
        "volRatio": 2.61,
        "cap": 23,
        "yang": 2,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "000757",
        "name": "浩物股份",
        "industry": "汽车服务",
        "price": 4.42,
        "gain": 3.03,
        "turnover": 2.87,
        "volRatio": 1.69,
        "cap": 24,
        "yang": 2,
        "aboveRate": 97,
        "sector": ""
      }
    ],
    "warnings": []
  },
  {
    "date": "2026-09-18",
    "runAt": "2026-09-18 23:09",
    "count": 29,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "002785",
        "name": "万里石",
        "industry": "装修建材",
        "price": 39.39,
        "gain": 6.72,
        "turnover": 5.09,
        "volRatio": 2.08,
        "cap": 89,
        "yang": 3,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "603321",
        "name": "梅轮电梯",
        "industry": "专用设备",
        "price": 7.18,
        "gain": 6.21,
        "turnover": 3.74,
        "volRatio": 1.09,
        "cap": 25,
        "yang": 4,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "605111",
        "name": "新洁能",
        "industry": "半导体",
        "price": 62.85,
        "gain": 6.11,
        "turnover": 6.59,
        "volRatio": 2.09,
        "cap": 261,
        "yang": 5,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "001360",
        "name": "南矿集团",
        "industry": "专用设备",
        "price": 20.56,
        "gain": 6.09,
        "turnover": 7.46,
        "volRatio": 1.65,
        "cap": 42,
        "yang": 4,
        "aboveRate": 97,
        "sector": ""
      },
      {
        "code": "000797",
        "name": "中国武夷",
        "industry": "房地产开发",
        "price": 2.69,
        "gain": 5.91,
        "turnover": 5.3,
        "volRatio": 2.4,
        "cap": 42,
        "yang": 3,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "600790",
        "name": "轻纺城",
        "industry": "一般零售",
        "price": 3.63,
        "gain": 5.83,
        "turnover": 3.41,
        "volRatio": 3.16,
        "cap": 53,
        "yang": 3,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "002881",
        "name": "美格智能",
        "industry": "通信设备",
        "price": 45.3,
        "gain": 5.79,
        "turnover": 7.24,
        "volRatio": 1.57,
        "cap": 137,
        "yang": 3,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "001312",
        "name": "福恩股份",
        "industry": "纺织制造",
        "price": 18.62,
        "gain": 5.56,
        "turnover": 13.03,
        "volRatio": 4.52,
        "cap": 43,
        "yang": 3,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "601595",
        "name": "上海电影",
        "industry": "影视院线",
        "price": 24.51,
        "gain": 5.51,
        "turnover": 4.35,
        "volRatio": 1.2,
        "cap": 110,
        "yang": 3,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "001393",
        "name": "维通利",
        "industry": "电网设备",
        "price": 43.9,
        "gain": 5.48,
        "turnover": 11.3,
        "volRatio": 2.52,
        "cap": 109,
        "yang": 5,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "600793",
        "name": "宜宾纸业",
        "industry": "造纸",
        "price": 17.3,
        "gain": 5.23,
        "turnover": 6.19,
        "volRatio": 1.87,
        "cap": 31,
        "yang": 3,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "001373",
        "name": "翔腾新材",
        "industry": "光学光电子",
        "price": 29.49,
        "gain": 4.87,
        "turnover": 6.5,
        "volRatio": 1.73,
        "cap": 20,
        "yang": 3,
        "aboveRate": 96,
        "sector": "算力/AI"
      },
      {
        "code": "600638",
        "name": "新黄浦",
        "industry": "房地产开发",
        "price": 4.99,
        "gain": 4.61,
        "turnover": 2.92,
        "volRatio": 2.39,
        "cap": 34,
        "yang": 3,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "001237",
        "name": "惠康科技",
        "industry": "通用设备",
        "price": 52.59,
        "gain": 4.57,
        "turnover": 9.72,
        "volRatio": 3.27,
        "cap": 78,
        "yang": 5,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "603976",
        "name": "正川股份",
        "industry": "医疗器械",
        "price": 30.29,
        "gain": 4.41,
        "turnover": 3.23,
        "volRatio": 1.17,
        "cap": 52,
        "yang": 3,
        "aboveRate": 97,
        "sector": "医药"
      },
      {
        "code": "603334",
        "name": "丰倍生物",
        "industry": "化学制品",
        "price": 31.45,
        "gain": 4.07,
        "turnover": 7.1,
        "volRatio": 2.81,
        "cap": 45,
        "yang": 5,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "600865",
        "name": "百大集团",
        "industry": "一般零售",
        "price": 10.86,
        "gain": 4.02,
        "turnover": 15.49,
        "volRatio": 1.03,
        "cap": 41,
        "yang": 3,
        "aboveRate": 95,
        "sector": ""
      },
      {
        "code": "000019",
        "name": "深粮控股",
        "industry": "农产品加工",
        "price": 7.15,
        "gain": 3.92,
        "turnover": 9.32,
        "volRatio": 1.23,
        "cap": 82,
        "yang": 3,
        "aboveRate": 97,
        "sector": ""
      },
      {
        "code": "601112",
        "name": "振石股份",
        "industry": "玻璃玻纤",
        "price": 17,
        "gain": 3.79,
        "turnover": 9.85,
        "volRatio": 1.54,
        "cap": 296,
        "yang": 2,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "002261",
        "name": "拓维信息",
        "industry": "软件开发",
        "price": 26,
        "gain": 3.59,
        "turnover": 5.87,
        "volRatio": 3.23,
        "cap": 328,
        "yang": 2,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "000782",
        "name": "恒申新材",
        "industry": "化学纤维",
        "price": 8.12,
        "gain": 3.57,
        "turnover": 3.62,
        "volRatio": 1.93,
        "cap": 56,
        "yang": 3,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "002981",
        "name": "朝阳科技",
        "industry": "消费电子",
        "price": 25.73,
        "gain": 3.33,
        "turnover": 6.35,
        "volRatio": 2.42,
        "cap": 35,
        "yang": 3,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "002106",
        "name": "莱宝高科",
        "industry": "光学光电子",
        "price": 12.52,
        "gain": 3.13,
        "turnover": 8.25,
        "volRatio": 1.59,
        "cap": 88,
        "yang": 3,
        "aboveRate": 97,
        "sector": "算力/AI"
      },
      {
        "code": "002489",
        "name": "浙江永强",
        "industry": "家居用品",
        "price": 3.13,
        "gain": 2.96,
        "turnover": 3.33,
        "volRatio": 1.39,
        "cap": 68,
        "yang": 3,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "002956",
        "name": "西麦食品",
        "industry": "休闲食品",
        "price": 17.8,
        "gain": 2.95,
        "turnover": 4.05,
        "volRatio": 1.72,
        "cap": 56,
        "yang": 3,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "001226",
        "name": "拓山重工",
        "industry": "工程机械",
        "price": 46,
        "gain": 2.93,
        "turnover": 2.5,
        "volRatio": 1.03,
        "cap": 34,
        "yang": 2,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "002522",
        "name": "浙江众成",
        "industry": "塑料",
        "price": 6.09,
        "gain": 2.7,
        "turnover": 12.32,
        "volRatio": 1.32,
        "cap": 55,
        "yang": 6,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "000571",
        "name": "新大洲A",
        "industry": "煤炭开采",
        "price": 6.55,
        "gain": 2.5,
        "turnover": 3.83,
        "volRatio": 1.29,
        "cap": 55,
        "yang": 5,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "002748",
        "name": "世龙实业",
        "industry": "化学原料",
        "price": 12.32,
        "gain": 2.5,
        "turnover": 2.53,
        "volRatio": 1.41,
        "cap": 30,
        "yang": 3,
        "aboveRate": 98,
        "sector": ""
      }
    ],
    "warnings": []
  },
  {
    "date": "2026-09-17",
    "runAt": "2026-09-17 15:20",
    "count": 2,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "603236",
        "name": "移远通信",
        "industry": "通信设备",
        "price": 73.66,
        "gain": 5.62,
        "turnover": 7.01,
        "volRatio": 1.56,
        "cap": 299,
        "yang": 3,
        "aboveRate": 97,
        "sector": "算力/AI"
      },
      {
        "code": "601579",
        "name": "会稽山",
        "industry": "非白酒",
        "price": 29.85,
        "gain": 5.37,
        "turnover": 8.64,
        "volRatio": 1.8,
        "cap": 143,
        "yang": 2,
        "aboveRate": 98,
        "sector": ""
      }
    ],
    "warnings": []
  },
  {
    "date": "2026-09-14",
    "runAt": "2026-09-14 18:12",
    "count": 25,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "002745",
        "name": "木林森",
        "industry": "光学光电子",
        "price": 11.92,
        "gain": 7,
        "turnover": 9.93,
        "volRatio": 2.33,
        "cap": 177,
        "yang": 2,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "002518",
        "name": "科士达",
        "industry": "其他电源设备Ⅱ",
        "price": 37.1,
        "gain": 6.79,
        "turnover": 5.97,
        "volRatio": 1.86,
        "cap": 216,
        "yang": 4,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "600353",
        "name": "旭光电子",
        "industry": "其他电子Ⅱ",
        "price": 33.2,
        "gain": 6.48,
        "turnover": 7.96,
        "volRatio": 1.38,
        "cap": 275,
        "yang": 2,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "600545",
        "name": "卓郎智能",
        "industry": "专用设备",
        "price": 4.45,
        "gain": 6.46,
        "turnover": 10.98,
        "volRatio": 2.48,
        "cap": 80,
        "yang": 6,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "002134",
        "name": "天津普林",
        "industry": "元件",
        "price": 24.71,
        "gain": 6.42,
        "turnover": 13.45,
        "volRatio": 2.87,
        "cap": 61,
        "yang": 4,
        "aboveRate": 99,
        "sector": "算力/AI"
      },
      {
        "code": "002119",
        "name": "康强电子",
        "industry": "半导体",
        "price": 24.13,
        "gain": 6.39,
        "turnover": 13.09,
        "volRatio": 1.95,
        "cap": 91,
        "yang": 3,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "001326",
        "name": "联域股份",
        "industry": "照明设备Ⅱ",
        "price": 78.95,
        "gain": 6.24,
        "turnover": 10.51,
        "volRatio": 1.35,
        "cap": 58,
        "yang": 2,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "603328",
        "name": "依顿电子",
        "industry": "元件",
        "price": 13.5,
        "gain": 5.72,
        "turnover": 10.68,
        "volRatio": 1.98,
        "cap": 135,
        "yang": 2,
        "aboveRate": 97,
        "sector": "算力/AI"
      },
      {
        "code": "002913",
        "name": "奥士康",
        "industry": "元件",
        "price": 76.54,
        "gain": 5.59,
        "turnover": 5.29,
        "volRatio": 1.14,
        "cap": 243,
        "yang": 4,
        "aboveRate": 100,
        "sector": "算力/AI"
      },
      {
        "code": "003006",
        "name": "百亚股份",
        "industry": "个护用品",
        "price": 19.2,
        "gain": 5.49,
        "turnover": 9.22,
        "volRatio": 1.58,
        "cap": 82,
        "yang": 10,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "605167",
        "name": "利柏特",
        "industry": "专业工程",
        "price": 17.25,
        "gain": 5.44,
        "turnover": 2.77,
        "volRatio": 2.35,
        "cap": 88,
        "yang": 2,
        "aboveRate": 95,
        "sector": ""
      },
      {
        "code": "002815",
        "name": "崇达技术",
        "industry": "元件",
        "price": 21.12,
        "gain": 5.18,
        "turnover": 19.83,
        "volRatio": 1.23,
        "cap": 261,
        "yang": 4,
        "aboveRate": 100,
        "sector": "PCB/覆铜板（CCL）"
      },
      {
        "code": "002859",
        "name": "洁美科技",
        "industry": "其他电子Ⅱ",
        "price": 67.17,
        "gain": 4.97,
        "turnover": 6.3,
        "volRatio": 2.01,
        "cap": 305,
        "yang": 3,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "603989",
        "name": "艾华集团",
        "industry": "元件",
        "price": 34.62,
        "gain": 4.81,
        "turnover": 10.93,
        "volRatio": 1.08,
        "cap": 138,
        "yang": 2,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "603386",
        "name": "骏亚科技",
        "industry": "元件",
        "price": 17.25,
        "gain": 4.8,
        "turnover": 12.7,
        "volRatio": 3.5,
        "cap": 56,
        "yang": 6,
        "aboveRate": 99,
        "sector": "算力/AI"
      },
      {
        "code": "603920",
        "name": "世运电路",
        "industry": "元件",
        "price": 43.42,
        "gain": 4.75,
        "turnover": 7.77,
        "volRatio": 1.72,
        "cap": 313,
        "yang": 6,
        "aboveRate": 99,
        "sector": "算力/AI"
      },
      {
        "code": "002925",
        "name": "盈趣科技",
        "industry": "消费电子",
        "price": 24.54,
        "gain": 4.38,
        "turnover": 3.52,
        "volRatio": 1.96,
        "cap": 189,
        "yang": 3,
        "aboveRate": 96,
        "sector": "算力/AI"
      },
      {
        "code": "603257",
        "name": "中国瑞林",
        "industry": "工程咨询服务Ⅱ",
        "price": 75.45,
        "gain": 3.93,
        "turnover": 10.57,
        "volRatio": 1.08,
        "cap": 91,
        "yang": 2,
        "aboveRate": 97,
        "sector": ""
      },
      {
        "code": "002106",
        "name": "莱宝高科",
        "industry": "光学光电子",
        "price": 11.58,
        "gain": 3.86,
        "turnover": 6.16,
        "volRatio": 2.18,
        "cap": 82,
        "yang": 2,
        "aboveRate": 100,
        "sector": "算力/AI"
      },
      {
        "code": "600206",
        "name": "有研新材",
        "industry": "半导体",
        "price": 47.25,
        "gain": 3.73,
        "turnover": 9.08,
        "volRatio": 1.07,
        "cap": 400,
        "yang": 3,
        "aboveRate": 98,
        "sector": "算力/AI"
      },
      {
        "code": "003013",
        "name": "地铁设计",
        "industry": "工程咨询服务Ⅱ",
        "price": 19.59,
        "gain": 3.71,
        "turnover": 3.89,
        "volRatio": 1.37,
        "cap": 90,
        "yang": 7,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "002138",
        "name": "顺络电子",
        "industry": "元件",
        "price": 49.79,
        "gain": 3.49,
        "turnover": 5.44,
        "volRatio": 1.48,
        "cap": 401,
        "yang": 2,
        "aboveRate": 100,
        "sector": "算力/AI"
      },
      {
        "code": "600552",
        "name": "凯盛科技",
        "industry": "光学光电子",
        "price": 17.18,
        "gain": 3.43,
        "turnover": 4.34,
        "volRatio": 1.18,
        "cap": 162,
        "yang": 4,
        "aboveRate": 99,
        "sector": "算力/AI"
      },
      {
        "code": "002845",
        "name": "同兴达",
        "industry": "光学光电子",
        "price": 13.87,
        "gain": 3.2,
        "turnover": 3.92,
        "volRatio": 1.51,
        "cap": 45,
        "yang": 2,
        "aboveRate": 99,
        "sector": "算力/AI"
      },
      {
        "code": "605589",
        "name": "圣泉集团",
        "industry": "塑料",
        "price": 39.04,
        "gain": 2.57,
        "turnover": 3.06,
        "volRatio": 1.29,
        "cap": 330,
        "yang": 3,
        "aboveRate": 96,
        "sector": ""
      }
    ]
  },
  {
    "date": "2026-09-10",
    "runAt": "2026-09-10 14:30",
    "count": 6,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "600101",
        "name": "明星电力",
        "industry": "电力",
        "price": 8.43,
        "gain": 6.04,
        "turnover": 8.94,
        "volRatio": 7.18,
        "cap": 46,
        "yang": 2,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "600113",
        "name": "浙江东日",
        "industry": "一般零售",
        "price": 34.18,
        "gain": 5.69,
        "turnover": 3.09,
        "volRatio": 1.92,
        "cap": 141,
        "yang": 2,
        "aboveRate": 97,
        "sector": "消费"
      },
      {
        "code": "002320",
        "name": "海峡股份",
        "industry": "航运港口",
        "price": 7.87,
        "gain": 4.93,
        "turnover": 4.66,
        "volRatio": 1.51,
        "cap": 176,
        "yang": 2,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "600726",
        "name": "华电能源",
        "industry": "电力",
        "price": 5.77,
        "gain": 4.91,
        "turnover": 2.83,
        "volRatio": 3.38,
        "cap": 456,
        "yang": 2,
        "aboveRate": 95,
        "sector": ""
      },
      {
        "code": "600391",
        "name": "航发科技",
        "industry": "航空装备Ⅱ",
        "price": 42.63,
        "gain": 4.28,
        "turnover": 7.37,
        "volRatio": 1.39,
        "cap": 141,
        "yang": 6,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "003006",
        "name": "百亚股份",
        "industry": "个护用品",
        "price": 17.11,
        "gain": 2.7,
        "turnover": 6.03,
        "volRatio": 1.89,
        "cap": 74,
        "yang": 7,
        "aboveRate": 100,
        "sector": ""
      }
    ]
  },
  {
    "date": "2026-09-08",
    "runAt": "2026-09-08 14:31",
    "count": 28,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "601086",
        "name": "国芳集团",
        "industry": "一般零售",
        "price": 14.82,
        "gain": 6.47,
        "turnover": 15.34,
        "volRatio": 2.05,
        "cap": 99,
        "yang": 2,
        "aboveRate": 99,
        "sector": "大消费"
      },
      {
        "code": "002637",
        "name": "赞宇科技",
        "industry": "化学制品",
        "price": 13.58,
        "gain": 6.26,
        "turnover": 10.95,
        "volRatio": 2.33,
        "cap": 64,
        "yang": 3,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "603991",
        "name": "领先股份",
        "industry": "半导体",
        "price": 177.67,
        "gain": 6.16,
        "turnover": 6.22,
        "volRatio": 1.42,
        "cap": 271,
        "yang": 2,
        "aboveRate": 96,
        "sector": "算力/AI"
      },
      {
        "code": "002219",
        "name": "新里程",
        "industry": "医疗服务",
        "price": 2.27,
        "gain": 5.58,
        "turnover": 4.29,
        "volRatio": 2.04,
        "cap": 78,
        "yang": 2,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "603600",
        "name": "永艺股份",
        "industry": "家居用品",
        "price": 10.93,
        "gain": 5.5,
        "turnover": 4.04,
        "volRatio": 2.6,
        "cap": 36,
        "yang": 4,
        "aboveRate": 97,
        "sector": "消费"
      },
      {
        "code": "000998",
        "name": "隆平高科",
        "industry": "种植业",
        "price": 10.21,
        "gain": 5.48,
        "turnover": 8.96,
        "volRatio": 1.63,
        "cap": 150,
        "yang": 2,
        "aboveRate": 99,
        "sector": "农业/种业"
      },
      {
        "code": "002661",
        "name": "克明食品",
        "industry": "食品加工",
        "price": 8.54,
        "gain": 5.43,
        "turnover": 5.11,
        "volRatio": 3.41,
        "cap": 28,
        "yang": 2,
        "aboveRate": 96,
        "sector": "消费"
      },
      {
        "code": "603336",
        "name": "宏辉果蔬",
        "industry": "种植业",
        "price": 9.87,
        "gain": 5.34,
        "turnover": 4.97,
        "volRatio": 1.5,
        "cap": 60,
        "yang": 2,
        "aboveRate": 98,
        "sector": "农业/种业"
      },
      {
        "code": "002081",
        "name": "金 螳 螂",
        "industry": "装修装饰Ⅱ",
        "price": 5.61,
        "gain": 5.25,
        "turnover": 14.57,
        "volRatio": 1.19,
        "cap": 149,
        "yang": 2,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "002166",
        "name": "莱茵生物",
        "industry": "化学制品",
        "price": 7.21,
        "gain": 4.95,
        "turnover": 3.91,
        "volRatio": 3.5,
        "cap": 53,
        "yang": 2,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "000525",
        "name": "红太阳",
        "industry": "农化制品",
        "price": 4.99,
        "gain": 4.61,
        "turnover": 3.86,
        "volRatio": 1.97,
        "cap": 65,
        "yang": 3,
        "aboveRate": 97,
        "sector": ""
      },
      {
        "code": "603086",
        "name": "先达股份",
        "industry": "农化制品",
        "price": 6.53,
        "gain": 4.31,
        "turnover": 7.27,
        "volRatio": 1.26,
        "cap": 28,
        "yang": 2,
        "aboveRate": 97,
        "sector": ""
      },
      {
        "code": "000713",
        "name": "国投丰乐",
        "industry": "种植业",
        "price": 7.08,
        "gain": 4.27,
        "turnover": 7.58,
        "volRatio": 1.15,
        "cap": 57,
        "yang": 3,
        "aboveRate": 98,
        "sector": "农业/种业"
      },
      {
        "code": "603212",
        "name": "赛伍技术",
        "industry": "光伏设备",
        "price": 11.63,
        "gain": 4.21,
        "turnover": 2.93,
        "volRatio": 2.25,
        "cap": 51,
        "yang": 2,
        "aboveRate": 95,
        "sector": "新能源/车"
      },
      {
        "code": "600866",
        "name": "星湖科技",
        "industry": "化学制品",
        "price": 4.6,
        "gain": 4.07,
        "turnover": 3.07,
        "volRatio": 2.35,
        "cap": 76,
        "yang": 2,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "002652",
        "name": "扬子新材",
        "industry": "装修建材",
        "price": 4.58,
        "gain": 3.85,
        "turnover": 6.14,
        "volRatio": 2.13,
        "cap": 23,
        "yang": 2,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "000153",
        "name": "丰原药业",
        "industry": "化学制药",
        "price": 6.51,
        "gain": 3.83,
        "turnover": 3.09,
        "volRatio": 1.56,
        "cap": 30,
        "yang": 2,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "002758",
        "name": "浙农股份",
        "industry": "综合Ⅱ",
        "price": 9.29,
        "gain": 3.8,
        "turnover": 3.09,
        "volRatio": 1.03,
        "cap": 48,
        "yang": 2,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "000019",
        "name": "深粮控股",
        "industry": "农产品加工",
        "price": 7.66,
        "gain": 3.79,
        "turnover": 8.26,
        "volRatio": 1.02,
        "cap": 88,
        "yang": 2,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "603739",
        "name": "蔚蓝生物",
        "industry": "化学制品",
        "price": 13.53,
        "gain": 3.76,
        "turnover": 2.91,
        "volRatio": 1.72,
        "cap": 34,
        "yang": 2,
        "aboveRate": 98,
        "sector": ""
      },
      {
        "code": "600313",
        "name": "农发种业",
        "industry": "种植业",
        "price": 8.08,
        "gain": 3.59,
        "turnover": 14.64,
        "volRatio": 1.37,
        "cap": 94,
        "yang": 3,
        "aboveRate": 97,
        "sector": "农业/种业"
      },
      {
        "code": "601615",
        "name": "明阳智能",
        "industry": "风电设备",
        "price": 9.67,
        "gain": 3.42,
        "turnover": 2.56,
        "volRatio": 1.02,
        "cap": 219,
        "yang": 2,
        "aboveRate": 97,
        "sector": ""
      },
      {
        "code": "002582",
        "name": "好想你",
        "industry": "休闲食品",
        "price": 10.88,
        "gain": 3.42,
        "turnover": 10.59,
        "volRatio": 1.88,
        "cap": 49,
        "yang": 2,
        "aboveRate": 99,
        "sector": "消费"
      },
      {
        "code": "603970",
        "name": "中农立华",
        "industry": "农化制品",
        "price": 11.9,
        "gain": 3.21,
        "turnover": 2.91,
        "volRatio": 1.53,
        "cap": 32,
        "yang": 2,
        "aboveRate": 97,
        "sector": ""
      },
      {
        "code": "002788",
        "name": "鹭燕医药",
        "industry": "医药商业",
        "price": 11.89,
        "gain": 3.03,
        "turnover": 5.58,
        "volRatio": 2.27,
        "cap": 46,
        "yang": 2,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "002679",
        "name": "福建金森",
        "industry": "林业Ⅱ",
        "price": 11.48,
        "gain": 2.78,
        "turnover": 10.87,
        "volRatio": 1.01,
        "cap": 27,
        "yang": 2,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "002174",
        "name": "游族网络",
        "industry": "游戏Ⅱ",
        "price": 12.55,
        "gain": 2.7,
        "turnover": 3.3,
        "volRatio": 1.11,
        "cap": 123,
        "yang": 4,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "603458",
        "name": "勘设股份",
        "industry": "工程咨询服务Ⅱ",
        "price": 10.71,
        "gain": 2.59,
        "turnover": 5.1,
        "volRatio": 1.07,
        "cap": 33,
        "yang": 2,
        "aboveRate": 97,
        "sector": ""
      }
    ]
  },
  {
    "date": "2026-09-07",
    "runAt": "2026-09-07 14:30",
    "count": 8,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "000417",
        "name": "合百集团",
        "industry": "一般零售",
        "price": 6.72,
        "gain": 6.67,
        "turnover": 11.7,
        "volRatio": 2.31,
        "cap": 52,
        "yang": 2,
        "aboveRate": 100,
        "sector": "消费"
      },
      {
        "code": "603322",
        "name": "超讯科技",
        "industry": "通信服务",
        "price": 28.7,
        "gain": 5.67,
        "turnover": 5.07,
        "volRatio": 1.75,
        "cap": 45,
        "yang": 2,
        "aboveRate": 96,
        "sector": "算力/AI"
      },
      {
        "code": "000880",
        "name": "潍柴重机",
        "industry": "通用设备",
        "price": 25.51,
        "gain": 4.98,
        "turnover": 9.31,
        "volRatio": 2.07,
        "cap": 118,
        "yang": 3,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "003006",
        "name": "百亚股份",
        "industry": "个护用品",
        "price": 15.35,
        "gain": 4.71,
        "turnover": 2.81,
        "volRatio": 1.63,
        "cap": 66,
        "yang": 4,
        "aboveRate": 100,
        "sector": ""
      },
      {
        "code": "002985",
        "name": "北摩高科",
        "industry": "航空装备Ⅱ",
        "price": 28.97,
        "gain": 4.55,
        "turnover": 2.89,
        "volRatio": 2.25,
        "cap": 96,
        "yang": 3,
        "aboveRate": 100,
        "sector": "军工"
      },
      {
        "code": "001360",
        "name": "南矿集团",
        "industry": "专用设备",
        "price": 19.31,
        "gain": 3.76,
        "turnover": 6.54,
        "volRatio": 1.45,
        "cap": 39,
        "yang": 3,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "002251",
        "name": "步步高",
        "industry": "一般零售",
        "price": 3.94,
        "gain": 3.68,
        "turnover": 5.56,
        "volRatio": 1.19,
        "cap": 106,
        "yang": 2,
        "aboveRate": 99,
        "sector": "消费"
      },
      {
        "code": "000501",
        "name": "武商集团",
        "industry": "一般零售",
        "price": 7.75,
        "gain": 2.65,
        "turnover": 3.04,
        "volRatio": 1.74,
        "cap": 60,
        "yang": 2,
        "aboveRate": 100,
        "sector": "消费"
      }
    ]
  },
  {
    "date": "2026-09-04",
    "runAt": "2026-09-04 14:30",
    "count": 7,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "600689",
        "name": "上海三毛",
        "industry": "综合Ⅱ",
        "price": 12.57,
        "gain": 6.35,
        "turnover": 5.17,
        "volRatio": 1.05,
        "cap": 25,
        "yang": 3,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "002438",
        "name": "江苏神通",
        "industry": "通用设备",
        "price": 14.57,
        "gain": 5.81,
        "turnover": 4.37,
        "volRatio": 6.26,
        "cap": 74,
        "yang": 2,
        "aboveRate": 96,
        "sector": ""
      },
      {
        "code": "600685",
        "name": "中船防务",
        "industry": "航海装备Ⅱ",
        "price": 27.64,
        "gain": 4.58,
        "turnover": 3.51,
        "volRatio": 2.88,
        "cap": 391,
        "yang": 3,
        "aboveRate": 100,
        "sector": "军工"
      },
      {
        "code": "601118",
        "name": "海南橡胶",
        "industry": "种植业",
        "price": 7.05,
        "gain": 3.83,
        "turnover": 4.23,
        "volRatio": 1.34,
        "cap": 302,
        "yang": 3,
        "aboveRate": 98,
        "sector": "农业/种业"
      },
      {
        "code": "600936",
        "name": "北投科技",
        "industry": "IT服务Ⅱ",
        "price": 5.47,
        "gain": 2.82,
        "turnover": 4.76,
        "volRatio": 1.33,
        "cap": 91,
        "yang": 4,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "601890",
        "name": "亚星锚链",
        "industry": "航海装备Ⅱ",
        "price": 9.19,
        "gain": 2.8,
        "turnover": 4.73,
        "volRatio": 1.88,
        "cap": 88,
        "yang": 8,
        "aboveRate": 99,
        "sector": "军工"
      },
      {
        "code": "000582",
        "name": "北部湾港",
        "industry": "航运港口",
        "price": 12.11,
        "gain": 2.63,
        "turnover": 2.84,
        "volRatio": 1.69,
        "cap": 305,
        "yang": 8,
        "aboveRate": 99,
        "sector": ""
      }
    ]
  }
];
