window.SCREENER = [
  {
    "date": "2026-09-24",
    "runAt": "2026-09-24 15:10",
    "count": 3,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": "≥1.5",
      "yang": "≥2连阳",
      "gain20": "≤25%（近 20 日）",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "600661",
        "name": "昂立教育",
        "industry": "教育",
        "price": 9.56,
        "gain": 5.87,
        "turnover": 8.24,
        "volRatio": 2.88,
        "cap": 27,
        "yang": 3,
        "gain20": 5.37,
        "aboveRate": 97,
        "sector": ""
      },
      {
        "code": "603073",
        "name": "彩蝶实业",
        "industry": "化学纤维",
        "price": 18.88,
        "gain": 4.31,
        "turnover": 4.71,
        "volRatio": 2,
        "cap": 22,
        "yang": 6,
        "gain20": 7.74,
        "aboveRate": 99,
        "sector": ""
      },
      {
        "code": "002638",
        "name": "勤上股份",
        "industry": "照明设备Ⅱ",
        "price": 4.93,
        "gain": 4.01,
        "turnover": 8.4,
        "volRatio": 3.67,
        "cap": 71,
        "yang": 6,
        "gain20": 5.33,
        "aboveRate": 98,
        "sector": ""
      }
    ],
    "warnings": []
  },
  {
    "date": "2026-09-22",
    "runAt": "2026-09-22 18:45",
    "count": 17,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "002129",
        "name": "TCL中环",
        "industry": "光伏设备",
        "price": 9.61,
        "gain": 6.54,
        "turnover": 5.42,
        "volRatio": 3.85,
        "cap": 389,
        "yang": 3,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": 0,
          "hit": false,
          "price": 9.61,
          "code": "002129",
          "at": "2026-09-23",
          "open": 9.6,
          "openPct": -0.1,
          "buyRet": 0.1,
          "netRet": -0.1,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603978",
        "name": "深圳新星",
        "industry": "金属新材料",
        "price": 26.2,
        "gain": 6.16,
        "turnover": 12.33,
        "volRatio": 1.4,
        "cap": 55,
        "yang": 7,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -1.83,
          "hit": false,
          "price": 25.72,
          "code": "603978",
          "at": "2026-09-23",
          "open": 26.21,
          "openPct": 0.04,
          "buyRet": -1.87,
          "netRet": -2.07,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002338",
        "name": "奥普光电",
        "industry": "军工电子Ⅱ",
        "price": 45.15,
        "gain": 5.99,
        "turnover": 3.77,
        "volRatio": 2.43,
        "cap": 108,
        "yang": 3,
        "aboveRate": 95,
        "sector": "",
        "verify": {
          "gain": 3.43,
          "hit": true,
          "price": 46.7,
          "code": "002338",
          "at": "2026-09-23",
          "open": 44.71,
          "openPct": -0.97,
          "buyRet": 4.45,
          "netRet": 4.24,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600605",
        "name": "汇通能源",
        "industry": "一般零售",
        "price": 28.74,
        "gain": 5.66,
        "turnover": 4.67,
        "volRatio": 2.35,
        "cap": 59,
        "yang": 5,
        "aboveRate": 98,
        "sector": "消费",
        "verify": {
          "gain": 9.99,
          "hit": true,
          "price": 31.61,
          "code": "600605",
          "at": "2026-09-23",
          "open": 28.93,
          "openPct": 0.66,
          "buyRet": 9.26,
          "netRet": 9.05,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600792",
        "name": "云煤能源",
        "industry": "焦炭Ⅱ",
        "price": 5.75,
        "gain": 5.31,
        "turnover": 16.53,
        "volRatio": 1.12,
        "cap": 64,
        "yang": 4,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -9.91,
          "hit": false,
          "price": 5.18,
          "code": "600792",
          "at": "2026-09-23",
          "open": 5.58,
          "openPct": -2.96,
          "buyRet": -7.17,
          "netRet": -7.35,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603073",
        "name": "彩蝶实业",
        "industry": "化学纤维",
        "price": 17.36,
        "gain": 5.21,
        "turnover": 2.84,
        "volRatio": 1.75,
        "cap": 20,
        "yang": 5,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": 4.26,
          "hit": true,
          "price": 18.1,
          "code": "603073",
          "at": "2026-09-23",
          "open": 17.4,
          "openPct": 0.23,
          "buyRet": 4.02,
          "netRet": 3.82,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600121",
        "name": "郑州煤电",
        "industry": "煤炭开采",
        "price": 5.27,
        "gain": 5.19,
        "turnover": 16.73,
        "volRatio": 1.35,
        "cap": 64,
        "yang": 5,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -8.73,
          "hit": false,
          "price": 4.81,
          "code": "600121",
          "at": "2026-09-23",
          "open": 5.15,
          "openPct": -2.28,
          "buyRet": -6.6,
          "netRet": -6.79,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "003033",
        "name": "征和工业",
        "industry": "摩托车及其他",
        "price": 89.3,
        "gain": 4.74,
        "turnover": 4.94,
        "volRatio": 1.44,
        "cap": 73,
        "yang": 5,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": 6.81,
          "hit": true,
          "price": 95.38,
          "code": "003033",
          "at": "2026-09-23",
          "open": 89.32,
          "openPct": 0.02,
          "buyRet": 6.78,
          "netRet": 6.57,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001368",
        "name": "通达创智",
        "industry": "文娱用品",
        "price": 34.84,
        "gain": 4.62,
        "turnover": 5.12,
        "volRatio": 1.14,
        "cap": 39,
        "yang": 5,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": 8.97,
          "hit": true,
          "price": 37.53,
          "code": "001368",
          "at": "2026-09-23",
          "open": 34.48,
          "openPct": 0.12,
          "buyRet": 8.85,
          "netRet": 8.63,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600828",
        "name": "茂业商业",
        "industry": "一般零售",
        "price": 4.62,
        "gain": 4.52,
        "turnover": 2.79,
        "volRatio": 1.33,
        "cap": 80,
        "yang": 5,
        "aboveRate": 95,
        "sector": "消费",
        "verify": {
          "gain": -4.76,
          "hit": false,
          "price": 4.4,
          "code": "600828",
          "at": "2026-09-23",
          "open": 4.56,
          "openPct": -1.3,
          "buyRet": -3.51,
          "netRet": -3.7,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000002",
        "name": "万  科Ａ",
        "industry": "房地产开发",
        "price": 3.81,
        "gain": 4.38,
        "turnover": 8.44,
        "volRatio": 2.8,
        "cap": 455,
        "yang": 5,
        "aboveRate": 95,
        "sector": "地产",
        "verify": {
          "gain": 2.89,
          "hit": true,
          "price": 3.92,
          "code": "000002",
          "at": "2026-09-23",
          "open": 3.81,
          "openPct": 0,
          "buyRet": 2.89,
          "netRet": 2.68,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603105",
        "name": "芯能科技",
        "industry": "电力",
        "price": 8.53,
        "gain": 4.28,
        "turnover": 7.63,
        "volRatio": 1.34,
        "cap": 43,
        "yang": 3,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -3.99,
          "hit": false,
          "price": 8.19,
          "code": "603105",
          "at": "2026-09-23",
          "open": 8.45,
          "openPct": -0.94,
          "buyRet": -3.08,
          "netRet": -3.27,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002333",
        "name": "罗普斯金",
        "industry": "装修建材",
        "price": 5.62,
        "gain": 4.27,
        "turnover": 2.94,
        "volRatio": 2.3,
        "cap": 38,
        "yang": 2,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": 3.02,
          "hit": true,
          "price": 5.79,
          "code": "002333",
          "at": "2026-09-23",
          "open": 5.63,
          "openPct": 0.18,
          "buyRet": 2.84,
          "netRet": 2.64,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600610",
        "name": "中毅达",
        "industry": "化学原料",
        "price": 8.11,
        "gain": 4.24,
        "turnover": 7.25,
        "volRatio": 2.12,
        "cap": 87,
        "yang": 4,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": -6.29,
          "hit": false,
          "price": 7.6,
          "code": "600610",
          "at": "2026-09-23",
          "open": 8.06,
          "openPct": -0.62,
          "buyRet": -5.71,
          "netRet": -5.9,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603271",
        "name": "永杰新材",
        "industry": "工业金属",
        "price": 40.38,
        "gain": 3.86,
        "turnover": 2.88,
        "volRatio": 2.42,
        "cap": 80,
        "yang": 3,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.96,
          "hit": false,
          "price": 39.59,
          "code": "603271",
          "at": "2026-09-23",
          "open": 40.3,
          "openPct": -0.2,
          "buyRet": -1.76,
          "netRet": -1.96,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002253",
        "name": "川大智胜",
        "industry": "软件开发",
        "price": 10.27,
        "gain": 3.63,
        "turnover": 4.23,
        "volRatio": 2.61,
        "cap": 23,
        "yang": 2,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": -10.03,
          "hit": false,
          "price": 9.24,
          "code": "002253",
          "at": "2026-09-23",
          "open": 9.24,
          "openPct": -10.03,
          "buyRet": 0,
          "netRet": null,
          "locked": true,
          "basis": "open-to-close",
          "by": "hist",
          "note": "一字板·无法买入（剔除）"
        }
      },
      {
        "code": "000757",
        "name": "浩物股份",
        "industry": "汽车服务",
        "price": 4.42,
        "gain": 3.03,
        "turnover": 2.87,
        "volRatio": 1.69,
        "cap": 24,
        "yang": 2,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": -1.81,
          "hit": false,
          "price": 4.34,
          "code": "000757",
          "at": "2026-09-23",
          "open": 4.38,
          "openPct": -0.9,
          "buyRet": -0.91,
          "netRet": -1.11,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      }
    ],
    "warnings": []
  },
  {
    "date": "2026-09-18",
    "runAt": "2026-09-18 23:09",
    "count": 29,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "002785",
        "name": "万里石",
        "industry": "装修建材",
        "price": 39.39,
        "gain": 6.72,
        "turnover": 5.09,
        "volRatio": 2.08,
        "cap": 89,
        "yang": 3,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": 7.13,
          "hit": true,
          "price": 42.2,
          "code": "002785",
          "at": "2026-09-21",
          "open": 40.96,
          "openPct": 3.99,
          "buyRet": 3.03,
          "netRet": 2.82,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603321",
        "name": "梅轮电梯",
        "industry": "专用设备",
        "price": 7.18,
        "gain": 6.21,
        "turnover": 3.74,
        "volRatio": 1.09,
        "cap": 25,
        "yang": 4,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": 5.57,
          "hit": true,
          "price": 7.58,
          "code": "603321",
          "at": "2026-09-21",
          "open": 7.41,
          "openPct": 3.2,
          "buyRet": 2.29,
          "netRet": 2.09,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "605111",
        "name": "新洁能",
        "industry": "半导体",
        "price": 62.85,
        "gain": 6.11,
        "turnover": 6.59,
        "volRatio": 2.09,
        "cap": 261,
        "yang": 5,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": -2.12,
          "hit": false,
          "price": 61.52,
          "code": "605111",
          "at": "2026-09-21",
          "open": 63,
          "openPct": 0.24,
          "buyRet": -2.35,
          "netRet": -2.54,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001360",
        "name": "南矿集团",
        "industry": "专用设备",
        "price": 20.56,
        "gain": 6.09,
        "turnover": 7.46,
        "volRatio": 1.65,
        "cap": 42,
        "yang": 4,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": 3.5,
          "hit": true,
          "price": 21.28,
          "code": "001360",
          "at": "2026-09-21",
          "open": 20.55,
          "openPct": -0.05,
          "buyRet": 3.55,
          "netRet": 3.35,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000797",
        "name": "中国武夷",
        "industry": "房地产开发",
        "price": 2.69,
        "gain": 5.91,
        "turnover": 5.3,
        "volRatio": 2.4,
        "cap": 42,
        "yang": 3,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": 1.12,
          "hit": true,
          "price": 2.72,
          "code": "000797",
          "at": "2026-09-21",
          "open": 2.66,
          "openPct": -1.12,
          "buyRet": 2.26,
          "netRet": 2.05,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600790",
        "name": "轻纺城",
        "industry": "一般零售",
        "price": 3.63,
        "gain": 5.83,
        "turnover": 3.41,
        "volRatio": 3.16,
        "cap": 53,
        "yang": 3,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": 1.38,
          "hit": true,
          "price": 3.68,
          "code": "600790",
          "at": "2026-09-21",
          "open": 3.61,
          "openPct": -0.55,
          "buyRet": 1.94,
          "netRet": 1.74,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002881",
        "name": "美格智能",
        "industry": "通信设备",
        "price": 45.3,
        "gain": 5.79,
        "turnover": 7.24,
        "volRatio": 1.57,
        "cap": 137,
        "yang": 3,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": 2.58,
          "hit": true,
          "price": 46.47,
          "code": "002881",
          "at": "2026-09-21",
          "open": 46.11,
          "openPct": 1.79,
          "buyRet": 0.78,
          "netRet": 0.58,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001312",
        "name": "福恩股份",
        "industry": "纺织制造",
        "price": 18.62,
        "gain": 5.56,
        "turnover": 13.03,
        "volRatio": 4.52,
        "cap": 43,
        "yang": 3,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": -1.4,
          "hit": false,
          "price": 18.36,
          "code": "001312",
          "at": "2026-09-21",
          "open": 18.5,
          "openPct": -0.64,
          "buyRet": -0.76,
          "netRet": -0.96,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "601595",
        "name": "上海电影",
        "industry": "影视院线",
        "price": 24.51,
        "gain": 5.51,
        "turnover": 4.35,
        "volRatio": 1.2,
        "cap": 110,
        "yang": 3,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -1.67,
          "hit": false,
          "price": 24.1,
          "code": "601595",
          "at": "2026-09-21",
          "open": 24.51,
          "openPct": 0,
          "buyRet": -1.67,
          "netRet": -1.87,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001393",
        "name": "维通利",
        "industry": "电网设备",
        "price": 43.9,
        "gain": 5.48,
        "turnover": 11.3,
        "volRatio": 2.52,
        "cap": 109,
        "yang": 5,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": -1.59,
          "hit": false,
          "price": 43.2,
          "code": "001393",
          "at": "2026-09-21",
          "open": 43.62,
          "openPct": -0.64,
          "buyRet": -0.96,
          "netRet": -1.16,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600793",
        "name": "宜宾纸业",
        "industry": "造纸",
        "price": 17.3,
        "gain": 5.23,
        "turnover": 6.19,
        "volRatio": 1.87,
        "cap": 31,
        "yang": 3,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": 2.77,
          "hit": true,
          "price": 17.78,
          "code": "600793",
          "at": "2026-09-21",
          "open": 17.3,
          "openPct": 0,
          "buyRet": 2.77,
          "netRet": 2.57,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001373",
        "name": "翔腾新材",
        "industry": "光学光电子",
        "price": 29.49,
        "gain": 4.87,
        "turnover": 6.5,
        "volRatio": 1.73,
        "cap": 20,
        "yang": 3,
        "aboveRate": 96,
        "sector": "算力/AI",
        "verify": {
          "gain": 10,
          "hit": true,
          "price": 32.44,
          "code": "001373",
          "at": "2026-09-21",
          "open": 29.63,
          "openPct": 0.47,
          "buyRet": 9.48,
          "netRet": 9.26,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600638",
        "name": "新黄浦",
        "industry": "房地产开发",
        "price": 4.99,
        "gain": 4.61,
        "turnover": 2.92,
        "volRatio": 2.39,
        "cap": 34,
        "yang": 3,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": 3.01,
          "hit": true,
          "price": 5.14,
          "code": "600638",
          "at": "2026-09-21",
          "open": 4.91,
          "openPct": -1.6,
          "buyRet": 4.68,
          "netRet": 4.48,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001237",
        "name": "惠康科技",
        "industry": "通用设备",
        "price": 52.59,
        "gain": 4.57,
        "turnover": 9.72,
        "volRatio": 3.27,
        "cap": 78,
        "yang": 5,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.37,
          "hit": false,
          "price": 51.87,
          "code": "001237",
          "at": "2026-09-21",
          "open": 52.02,
          "openPct": -1.08,
          "buyRet": -0.29,
          "netRet": -0.49,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603976",
        "name": "正川股份",
        "industry": "医疗器械",
        "price": 30.29,
        "gain": 4.41,
        "turnover": 3.23,
        "volRatio": 1.17,
        "cap": 52,
        "yang": 3,
        "aboveRate": 97,
        "sector": "医药",
        "verify": {
          "gain": 5.78,
          "hit": true,
          "price": 32.04,
          "code": "603976",
          "at": "2026-09-21",
          "open": 30.5,
          "openPct": 0.69,
          "buyRet": 5.05,
          "netRet": 4.84,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603334",
        "name": "丰倍生物",
        "industry": "化学制品",
        "price": 31.45,
        "gain": 4.07,
        "turnover": 7.1,
        "volRatio": 2.81,
        "cap": 45,
        "yang": 5,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": 2.86,
          "hit": true,
          "price": 32.35,
          "code": "603334",
          "at": "2026-09-21",
          "open": 31.39,
          "openPct": -0.19,
          "buyRet": 3.06,
          "netRet": 2.85,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600865",
        "name": "百大集团",
        "industry": "一般零售",
        "price": 10.86,
        "gain": 4.02,
        "turnover": 15.49,
        "volRatio": 1.03,
        "cap": 41,
        "yang": 3,
        "aboveRate": 95,
        "sector": "",
        "verify": {
          "gain": 5.34,
          "hit": true,
          "price": 11.44,
          "code": "600865",
          "at": "2026-09-21",
          "open": 10.91,
          "openPct": 0.46,
          "buyRet": 4.86,
          "netRet": 4.65,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000019",
        "name": "深粮控股",
        "industry": "农产品加工",
        "price": 7.15,
        "gain": 3.92,
        "turnover": 9.32,
        "volRatio": 1.23,
        "cap": 82,
        "yang": 3,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": 0.7,
          "hit": true,
          "price": 7.2,
          "code": "000019",
          "at": "2026-09-21",
          "open": 7.1,
          "openPct": -0.7,
          "buyRet": 1.41,
          "netRet": 1.21,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "601112",
        "name": "振石股份",
        "industry": "玻璃玻纤",
        "price": 17,
        "gain": 3.79,
        "turnover": 9.85,
        "volRatio": 1.54,
        "cap": 296,
        "yang": 2,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": 1,
          "hit": true,
          "price": 17.17,
          "code": "601112",
          "at": "2026-09-21",
          "open": 16.67,
          "openPct": -1.94,
          "buyRet": 3,
          "netRet": 2.79,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002261",
        "name": "拓维信息",
        "industry": "软件开发",
        "price": 26,
        "gain": 3.59,
        "turnover": 5.87,
        "volRatio": 3.23,
        "cap": 328,
        "yang": 2,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": -0.23,
          "hit": false,
          "price": 25.94,
          "code": "002261",
          "at": "2026-09-21",
          "open": 25.74,
          "openPct": -1,
          "buyRet": 0.78,
          "netRet": 0.58,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000782",
        "name": "恒申新材",
        "industry": "化学纤维",
        "price": 8.12,
        "gain": 3.57,
        "turnover": 3.62,
        "volRatio": 1.93,
        "cap": 56,
        "yang": 3,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": 2.22,
          "hit": true,
          "price": 8.3,
          "code": "000782",
          "at": "2026-09-21",
          "open": 8.13,
          "openPct": 0.12,
          "buyRet": 2.09,
          "netRet": 1.89,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002981",
        "name": "朝阳科技",
        "industry": "消费电子",
        "price": 25.73,
        "gain": 3.33,
        "turnover": 6.35,
        "volRatio": 2.42,
        "cap": 35,
        "yang": 3,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": 3.03,
          "hit": true,
          "price": 26.51,
          "code": "002981",
          "at": "2026-09-21",
          "open": 24.96,
          "openPct": -2.99,
          "buyRet": 6.21,
          "netRet": 6,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002106",
        "name": "莱宝高科",
        "industry": "光学光电子",
        "price": 12.52,
        "gain": 3.13,
        "turnover": 8.25,
        "volRatio": 1.59,
        "cap": 88,
        "yang": 3,
        "aboveRate": 97,
        "sector": "算力/AI",
        "verify": {
          "gain": -0.56,
          "hit": false,
          "price": 12.45,
          "code": "002106",
          "at": "2026-09-21",
          "open": 12.4,
          "openPct": -0.96,
          "buyRet": 0.4,
          "netRet": 0.2,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002489",
        "name": "浙江永强",
        "industry": "家居用品",
        "price": 3.13,
        "gain": 2.96,
        "turnover": 3.33,
        "volRatio": 1.39,
        "cap": 68,
        "yang": 3,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -0.32,
          "hit": false,
          "price": 3.12,
          "code": "002489",
          "at": "2026-09-21",
          "open": 3.15,
          "openPct": 0.64,
          "buyRet": -0.95,
          "netRet": -1.15,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002956",
        "name": "西麦食品",
        "industry": "休闲食品",
        "price": 17.8,
        "gain": 2.95,
        "turnover": 4.05,
        "volRatio": 1.72,
        "cap": 56,
        "yang": 3,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": 2.81,
          "hit": true,
          "price": 18.3,
          "code": "002956",
          "at": "2026-09-21",
          "open": 17.72,
          "openPct": -0.45,
          "buyRet": 3.27,
          "netRet": 3.07,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001226",
        "name": "拓山重工",
        "industry": "工程机械",
        "price": 46,
        "gain": 2.93,
        "turnover": 2.5,
        "volRatio": 1.03,
        "cap": 34,
        "yang": 2,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": 0.2,
          "hit": true,
          "price": 46.09,
          "code": "001226",
          "at": "2026-09-21",
          "open": 45.99,
          "openPct": -0.02,
          "buyRet": 0.22,
          "netRet": 0.02,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002522",
        "name": "浙江众成",
        "industry": "塑料",
        "price": 6.09,
        "gain": 2.7,
        "turnover": 12.32,
        "volRatio": 1.32,
        "cap": 55,
        "yang": 6,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": 2.63,
          "hit": true,
          "price": 6.25,
          "code": "002522",
          "at": "2026-09-21",
          "open": 6.02,
          "openPct": -1.15,
          "buyRet": 3.82,
          "netRet": 3.61,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000571",
        "name": "新大洲A",
        "industry": "煤炭开采",
        "price": 6.55,
        "gain": 2.5,
        "turnover": 3.83,
        "volRatio": 1.29,
        "cap": 55,
        "yang": 5,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": 1.53,
          "hit": true,
          "price": 6.65,
          "code": "000571",
          "at": "2026-09-21",
          "open": 6.6,
          "openPct": 0.76,
          "buyRet": 0.76,
          "netRet": 0.56,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002748",
        "name": "世龙实业",
        "industry": "化学原料",
        "price": 12.32,
        "gain": 2.5,
        "turnover": 2.53,
        "volRatio": 1.41,
        "cap": 30,
        "yang": 3,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -0.08,
          "hit": false,
          "price": 12.31,
          "code": "002748",
          "at": "2026-09-21",
          "open": 12.3,
          "openPct": -0.16,
          "buyRet": 0.08,
          "netRet": -0.12,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      }
    ],
    "warnings": []
  },
  {
    "date": "2026-09-17",
    "runAt": "2026-09-17 15:20",
    "count": 2,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "603236",
        "name": "移远通信",
        "industry": "通信设备",
        "price": 73.66,
        "gain": 5.62,
        "turnover": 7.01,
        "volRatio": 1.56,
        "cap": 299,
        "yang": 3,
        "aboveRate": 97,
        "sector": "算力/AI",
        "verify": {
          "gain": -1.52,
          "hit": false,
          "price": 72.54,
          "code": "603236",
          "at": "2026-09-18",
          "open": 73.65,
          "openPct": -0.01,
          "buyRet": -1.51,
          "netRet": -1.7,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "601579",
        "name": "会稽山",
        "industry": "非白酒",
        "price": 29.85,
        "gain": 5.37,
        "turnover": 8.64,
        "volRatio": 1.8,
        "cap": 143,
        "yang": 2,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": 10.02,
          "hit": true,
          "price": 32.84,
          "code": "601579",
          "at": "2026-09-18",
          "open": 30.11,
          "openPct": 0.87,
          "buyRet": 9.07,
          "netRet": 8.85,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      }
    ],
    "warnings": []
  },
  {
    "date": "2026-09-14",
    "runAt": "2026-09-14 18:12",
    "count": 25,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "002745",
        "name": "木林森",
        "industry": "光学光电子",
        "price": 11.92,
        "gain": 7,
        "turnover": 9.93,
        "volRatio": 2.33,
        "cap": 177,
        "yang": 2,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": -0.5,
          "hit": false,
          "price": 11.86,
          "code": "002745",
          "at": "2026-09-15",
          "open": 11.93,
          "openPct": 0.08,
          "buyRet": -0.59,
          "netRet": -0.79,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002518",
        "name": "科士达",
        "industry": "其他电源设备Ⅱ",
        "price": 37.1,
        "gain": 6.79,
        "turnover": 5.97,
        "volRatio": 1.86,
        "cap": 216,
        "yang": 4,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.11,
          "hit": false,
          "price": 36.69,
          "code": "002518",
          "at": "2026-09-15",
          "open": 37.14,
          "openPct": 0.11,
          "buyRet": -1.21,
          "netRet": -1.41,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600353",
        "name": "旭光电子",
        "industry": "其他电子Ⅱ",
        "price": 33.2,
        "gain": 6.48,
        "turnover": 7.96,
        "volRatio": 1.38,
        "cap": 275,
        "yang": 2,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.36,
          "hit": false,
          "price": 32.75,
          "code": "600353",
          "at": "2026-09-15",
          "open": 33.46,
          "openPct": 0.78,
          "buyRet": -2.12,
          "netRet": -2.32,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600545",
        "name": "卓郎智能",
        "industry": "专用设备",
        "price": 4.45,
        "gain": 6.46,
        "turnover": 10.98,
        "volRatio": 2.48,
        "cap": 80,
        "yang": 6,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": -3.6,
          "hit": false,
          "price": 4.29,
          "code": "600545",
          "at": "2026-09-15",
          "open": 4.42,
          "openPct": -0.67,
          "buyRet": -2.94,
          "netRet": -3.14,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002134",
        "name": "天津普林",
        "industry": "元件",
        "price": 24.71,
        "gain": 6.42,
        "turnover": 13.45,
        "volRatio": 2.87,
        "cap": 61,
        "yang": 4,
        "aboveRate": 99,
        "sector": "算力/AI",
        "verify": {
          "gain": -1.54,
          "hit": false,
          "price": 24.33,
          "code": "002134",
          "at": "2026-09-15",
          "open": 24.6,
          "openPct": -0.45,
          "buyRet": -1.1,
          "netRet": -1.3,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002119",
        "name": "康强电子",
        "industry": "半导体",
        "price": 24.13,
        "gain": 6.39,
        "turnover": 13.09,
        "volRatio": 1.95,
        "cap": 91,
        "yang": 3,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": -1.28,
          "hit": false,
          "price": 23.82,
          "code": "002119",
          "at": "2026-09-15",
          "open": 23.7,
          "openPct": -1.78,
          "buyRet": 0.51,
          "netRet": 0.31,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001326",
        "name": "联域股份",
        "industry": "照明设备Ⅱ",
        "price": 78.95,
        "gain": 6.24,
        "turnover": 10.51,
        "volRatio": 1.35,
        "cap": 58,
        "yang": 2,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.66,
          "hit": false,
          "price": 77.64,
          "code": "001326",
          "at": "2026-09-15",
          "open": 78.47,
          "openPct": -0.61,
          "buyRet": -1.06,
          "netRet": -1.26,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603328",
        "name": "依顿电子",
        "industry": "元件",
        "price": 13.5,
        "gain": 5.72,
        "turnover": 10.68,
        "volRatio": 1.98,
        "cap": 135,
        "yang": 2,
        "aboveRate": 97,
        "sector": "算力/AI",
        "verify": {
          "gain": -3.63,
          "hit": false,
          "price": 13.01,
          "code": "603328",
          "at": "2026-09-15",
          "open": 13.46,
          "openPct": -0.3,
          "buyRet": -3.34,
          "netRet": -3.54,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002913",
        "name": "奥士康",
        "industry": "元件",
        "price": 76.54,
        "gain": 5.59,
        "turnover": 5.29,
        "volRatio": 1.14,
        "cap": 243,
        "yang": 4,
        "aboveRate": 100,
        "sector": "算力/AI",
        "verify": {
          "gain": -1.29,
          "hit": false,
          "price": 75.55,
          "code": "002913",
          "at": "2026-09-15",
          "open": 75.5,
          "openPct": -1.36,
          "buyRet": 0.07,
          "netRet": -0.13,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "003006",
        "name": "百亚股份",
        "industry": "个护用品",
        "price": 19.2,
        "gain": 5.49,
        "turnover": 9.22,
        "volRatio": 1.58,
        "cap": 82,
        "yang": 10,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": -5.31,
          "hit": false,
          "price": 18.18,
          "code": "003006",
          "at": "2026-09-15",
          "open": 19.33,
          "openPct": 0.68,
          "buyRet": -5.95,
          "netRet": -6.14,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "605167",
        "name": "利柏特",
        "industry": "专业工程",
        "price": 17.25,
        "gain": 5.44,
        "turnover": 2.77,
        "volRatio": 2.35,
        "cap": 88,
        "yang": 2,
        "aboveRate": 95,
        "sector": "",
        "verify": {
          "gain": -5.22,
          "hit": false,
          "price": 16.35,
          "code": "605167",
          "at": "2026-09-15",
          "open": 17.1,
          "openPct": -0.87,
          "buyRet": -4.39,
          "netRet": -4.58,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002815",
        "name": "崇达技术",
        "industry": "元件",
        "price": 21.12,
        "gain": 5.18,
        "turnover": 19.83,
        "volRatio": 1.23,
        "cap": 261,
        "yang": 4,
        "aboveRate": 100,
        "sector": "PCB/覆铜板（CCL）",
        "verify": {
          "gain": 2.56,
          "hit": true,
          "price": 21.66,
          "code": "002815",
          "at": "2026-09-15",
          "open": 21.12,
          "openPct": 0,
          "buyRet": 2.56,
          "netRet": 2.35,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002859",
        "name": "洁美科技",
        "industry": "其他电子Ⅱ",
        "price": 67.17,
        "gain": 4.97,
        "turnover": 6.3,
        "volRatio": 2.01,
        "cap": 305,
        "yang": 3,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": -1.47,
          "hit": false,
          "price": 66.18,
          "code": "002859",
          "at": "2026-09-15",
          "open": 67.23,
          "openPct": 0.09,
          "buyRet": -1.56,
          "netRet": -1.76,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603989",
        "name": "艾华集团",
        "industry": "元件",
        "price": 34.62,
        "gain": 4.81,
        "turnover": 10.93,
        "volRatio": 1.08,
        "cap": 138,
        "yang": 2,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": 4.88,
          "hit": true,
          "price": 36.31,
          "code": "603989",
          "at": "2026-09-15",
          "open": 34.29,
          "openPct": -0.95,
          "buyRet": 5.89,
          "netRet": 5.68,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603386",
        "name": "骏亚科技",
        "industry": "元件",
        "price": 17.25,
        "gain": 4.8,
        "turnover": 12.7,
        "volRatio": 3.5,
        "cap": 56,
        "yang": 6,
        "aboveRate": 99,
        "sector": "算力/AI",
        "verify": {
          "gain": 8.12,
          "hit": true,
          "price": 18.65,
          "code": "603386",
          "at": "2026-09-15",
          "open": 17,
          "openPct": -1.45,
          "buyRet": 9.71,
          "netRet": 9.49,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603920",
        "name": "世运电路",
        "industry": "元件",
        "price": 43.42,
        "gain": 4.75,
        "turnover": 7.77,
        "volRatio": 1.72,
        "cap": 313,
        "yang": 6,
        "aboveRate": 99,
        "sector": "算力/AI",
        "verify": {
          "gain": -2.23,
          "hit": false,
          "price": 42.45,
          "code": "603920",
          "at": "2026-09-15",
          "open": 42.8,
          "openPct": -1.43,
          "buyRet": -0.82,
          "netRet": -1.02,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002925",
        "name": "盈趣科技",
        "industry": "消费电子",
        "price": 24.54,
        "gain": 4.38,
        "turnover": 3.52,
        "volRatio": 1.96,
        "cap": 189,
        "yang": 3,
        "aboveRate": 96,
        "sector": "算力/AI",
        "verify": {
          "gain": -1.43,
          "hit": false,
          "price": 24.19,
          "code": "002925",
          "at": "2026-09-15",
          "open": 24.6,
          "openPct": 0.24,
          "buyRet": -1.67,
          "netRet": -1.86,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603257",
        "name": "中国瑞林",
        "industry": "工程咨询服务Ⅱ",
        "price": 75.45,
        "gain": 3.93,
        "turnover": 10.57,
        "volRatio": 1.08,
        "cap": 91,
        "yang": 2,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": -3.99,
          "hit": false,
          "price": 72.44,
          "code": "603257",
          "at": "2026-09-15",
          "open": 74.02,
          "openPct": -1.9,
          "buyRet": -2.13,
          "netRet": -2.33,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002106",
        "name": "莱宝高科",
        "industry": "光学光电子",
        "price": 11.58,
        "gain": 3.86,
        "turnover": 6.16,
        "volRatio": 2.18,
        "cap": 82,
        "yang": 2,
        "aboveRate": 100,
        "sector": "算力/AI",
        "verify": {
          "gain": -1.81,
          "hit": false,
          "price": 11.37,
          "code": "002106",
          "at": "2026-09-15",
          "open": 11.5,
          "openPct": -0.69,
          "buyRet": -1.13,
          "netRet": -1.33,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600206",
        "name": "有研新材",
        "industry": "半导体",
        "price": 47.25,
        "gain": 3.73,
        "turnover": 9.08,
        "volRatio": 1.07,
        "cap": 400,
        "yang": 3,
        "aboveRate": 98,
        "sector": "算力/AI",
        "verify": {
          "gain": -0.66,
          "hit": false,
          "price": 46.94,
          "code": "600206",
          "at": "2026-09-15",
          "open": 46.6,
          "openPct": -1.38,
          "buyRet": 0.73,
          "netRet": 0.53,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "003013",
        "name": "地铁设计",
        "industry": "工程咨询服务Ⅱ",
        "price": 19.59,
        "gain": 3.71,
        "turnover": 3.89,
        "volRatio": 1.37,
        "cap": 90,
        "yang": 7,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -10.01,
          "hit": false,
          "price": 17.63,
          "code": "003013",
          "at": "2026-09-15",
          "open": 19.43,
          "openPct": -0.82,
          "buyRet": -9.26,
          "netRet": -9.45,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002138",
        "name": "顺络电子",
        "industry": "元件",
        "price": 49.79,
        "gain": 3.49,
        "turnover": 5.44,
        "volRatio": 1.48,
        "cap": 401,
        "yang": 2,
        "aboveRate": 100,
        "sector": "算力/AI",
        "verify": {
          "gain": -0.86,
          "hit": false,
          "price": 49.36,
          "code": "002138",
          "at": "2026-09-15",
          "open": 49.12,
          "openPct": -1.35,
          "buyRet": 0.49,
          "netRet": 0.29,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600552",
        "name": "凯盛科技",
        "industry": "光学光电子",
        "price": 17.18,
        "gain": 3.43,
        "turnover": 4.34,
        "volRatio": 1.18,
        "cap": 162,
        "yang": 4,
        "aboveRate": 99,
        "sector": "算力/AI",
        "verify": {
          "gain": -0.64,
          "hit": false,
          "price": 17.07,
          "code": "600552",
          "at": "2026-09-15",
          "open": 17,
          "openPct": -1.05,
          "buyRet": 0.41,
          "netRet": 0.21,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002845",
        "name": "同兴达",
        "industry": "光学光电子",
        "price": 13.87,
        "gain": 3.2,
        "turnover": 3.92,
        "volRatio": 1.51,
        "cap": 45,
        "yang": 2,
        "aboveRate": 99,
        "sector": "算力/AI",
        "verify": {
          "gain": -1.15,
          "hit": false,
          "price": 13.71,
          "code": "002845",
          "at": "2026-09-15",
          "open": 13.8,
          "openPct": -0.5,
          "buyRet": -0.65,
          "netRet": -0.85,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "605589",
        "name": "圣泉集团",
        "industry": "塑料",
        "price": 39.04,
        "gain": 2.57,
        "turnover": 3.06,
        "volRatio": 1.29,
        "cap": 330,
        "yang": 3,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": 1.43,
          "hit": true,
          "price": 39.6,
          "code": "605589",
          "at": "2026-09-15",
          "open": 38.78,
          "openPct": -0.67,
          "buyRet": 2.11,
          "netRet": 1.91,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      }
    ]
  },
  {
    "date": "2026-09-10",
    "runAt": "2026-09-10 14:30",
    "count": 6,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "600101",
        "name": "明星电力",
        "industry": "电力",
        "price": 8.43,
        "gain": 6.04,
        "turnover": 8.94,
        "volRatio": 7.18,
        "cap": 46,
        "yang": 2,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": -3.42,
          "hit": false,
          "price": 8.2,
          "code": "600101",
          "at": "2026-09-11",
          "open": 8.25,
          "openPct": -2.83,
          "buyRet": -0.61,
          "netRet": -0.8,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600113",
        "name": "浙江东日",
        "industry": "一般零售",
        "price": 34.18,
        "gain": 5.69,
        "turnover": 3.09,
        "volRatio": 1.92,
        "cap": 141,
        "yang": 2,
        "aboveRate": 97,
        "sector": "消费",
        "verify": {
          "gain": -8,
          "hit": false,
          "price": 31.4,
          "code": "600113",
          "at": "2026-09-11",
          "open": 33.73,
          "openPct": -1.17,
          "buyRet": -6.91,
          "netRet": -7.09,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002320",
        "name": "海峡股份",
        "industry": "航运港口",
        "price": 7.87,
        "gain": 4.93,
        "turnover": 4.66,
        "volRatio": 1.51,
        "cap": 176,
        "yang": 2,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": -8.81,
          "hit": false,
          "price": 7.14,
          "code": "002320",
          "at": "2026-09-11",
          "open": 7.68,
          "openPct": -1.92,
          "buyRet": -7.03,
          "netRet": -7.22,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600726",
        "name": "华电能源",
        "industry": "电力",
        "price": 5.77,
        "gain": 4.91,
        "turnover": 2.83,
        "volRatio": 3.38,
        "cap": 456,
        "yang": 2,
        "aboveRate": 95,
        "sector": "",
        "verify": {
          "gain": -5.84,
          "hit": false,
          "price": 5.48,
          "code": "600726",
          "at": "2026-09-11",
          "open": 5.81,
          "openPct": -0.17,
          "buyRet": -5.68,
          "netRet": -5.87,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600391",
        "name": "航发科技",
        "industry": "航空装备Ⅱ",
        "price": 42.63,
        "gain": 4.28,
        "turnover": 7.37,
        "volRatio": 1.39,
        "cap": 141,
        "yang": 6,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": 3.12,
          "hit": true,
          "price": 43.93,
          "code": "600391",
          "at": "2026-09-11",
          "open": 42.41,
          "openPct": -0.45,
          "buyRet": 3.58,
          "netRet": 3.38,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "003006",
        "name": "百亚股份",
        "industry": "个护用品",
        "price": 17.11,
        "gain": 2.7,
        "turnover": 6.03,
        "volRatio": 1.89,
        "cap": 74,
        "yang": 7,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": 6.43,
          "hit": true,
          "price": 18.2,
          "code": "003006",
          "at": "2026-09-11",
          "open": 17.19,
          "openPct": 0.53,
          "buyRet": 5.88,
          "netRet": 5.66,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      }
    ]
  },
  {
    "date": "2026-09-08",
    "runAt": "2026-09-08 14:31",
    "count": 28,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "601086",
        "name": "国芳集团",
        "industry": "一般零售",
        "price": 14.82,
        "gain": 6.47,
        "turnover": 15.34,
        "volRatio": 2.05,
        "cap": 99,
        "yang": 2,
        "aboveRate": 99,
        "sector": "大消费",
        "verify": {
          "gain": -0.47,
          "hit": false,
          "price": 14.88,
          "code": "601086",
          "at": "2026-09-09",
          "open": 14.8,
          "openPct": -1,
          "buyRet": 0.54,
          "netRet": 0.34,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002637",
        "name": "赞宇科技",
        "industry": "化学制品",
        "price": 13.58,
        "gain": 6.26,
        "turnover": 10.95,
        "volRatio": 2.33,
        "cap": 64,
        "yang": 3,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": -0.89,
          "hit": false,
          "price": 13.43,
          "code": "002637",
          "at": "2026-09-09",
          "open": 13.39,
          "openPct": -1.18,
          "buyRet": 0.3,
          "netRet": 0.1,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603991",
        "name": "领先股份",
        "industry": "半导体",
        "price": 177.67,
        "gain": 6.16,
        "turnover": 6.22,
        "volRatio": 1.42,
        "cap": 271,
        "yang": 2,
        "aboveRate": 96,
        "sector": "算力/AI",
        "verify": {
          "gain": 1.68,
          "hit": true,
          "price": 180.4,
          "code": "603991",
          "at": "2026-09-09",
          "open": 177.42,
          "openPct": 0,
          "buyRet": 1.68,
          "netRet": 1.48,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002219",
        "name": "新里程",
        "industry": "医疗服务",
        "price": 2.27,
        "gain": 5.58,
        "turnover": 4.29,
        "volRatio": 2.04,
        "cap": 78,
        "yang": 2,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -3.1,
          "hit": false,
          "price": 2.19,
          "code": "002219",
          "at": "2026-09-09",
          "open": 2.25,
          "openPct": -0.44,
          "buyRet": -2.67,
          "netRet": -2.86,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603600",
        "name": "永艺股份",
        "industry": "家居用品",
        "price": 10.93,
        "gain": 5.5,
        "turnover": 4.04,
        "volRatio": 2.6,
        "cap": 36,
        "yang": 4,
        "aboveRate": 97,
        "sector": "消费",
        "verify": {
          "gain": 1.12,
          "hit": true,
          "price": 10.84,
          "code": "603600",
          "at": "2026-09-09",
          "open": 10.74,
          "openPct": 0.19,
          "buyRet": 0.93,
          "netRet": 0.73,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000998",
        "name": "隆平高科",
        "industry": "种植业",
        "price": 10.21,
        "gain": 5.48,
        "turnover": 8.96,
        "volRatio": 1.63,
        "cap": 150,
        "yang": 2,
        "aboveRate": 99,
        "sector": "农业/种业",
        "verify": {
          "gain": -1.28,
          "hit": false,
          "price": 10.02,
          "code": "000998",
          "at": "2026-09-09",
          "open": 9.9,
          "openPct": -2.46,
          "buyRet": 1.21,
          "netRet": 1.01,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002661",
        "name": "克明食品",
        "industry": "食品加工",
        "price": 8.54,
        "gain": 5.43,
        "turnover": 5.11,
        "volRatio": 3.41,
        "cap": 28,
        "yang": 2,
        "aboveRate": 96,
        "sector": "消费",
        "verify": {
          "gain": 0.58,
          "hit": true,
          "price": 8.73,
          "code": "002661",
          "at": "2026-09-09",
          "open": 8.46,
          "openPct": -2.53,
          "buyRet": 3.19,
          "netRet": 2.99,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603336",
        "name": "宏辉果蔬",
        "industry": "种植业",
        "price": 9.87,
        "gain": 5.34,
        "turnover": 4.97,
        "volRatio": 1.5,
        "cap": 60,
        "yang": 2,
        "aboveRate": 98,
        "sector": "农业/种业",
        "verify": {
          "gain": -2.02,
          "hit": false,
          "price": 9.68,
          "code": "603336",
          "at": "2026-09-09",
          "open": 9.8,
          "openPct": -0.81,
          "buyRet": -1.22,
          "netRet": -1.42,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002081",
        "name": "金 螳 螂",
        "industry": "装修装饰Ⅱ",
        "price": 5.61,
        "gain": 5.25,
        "turnover": 14.57,
        "volRatio": 1.19,
        "cap": 149,
        "yang": 2,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -6.83,
          "hit": false,
          "price": 5.18,
          "code": "002081",
          "at": "2026-09-09",
          "open": 5.5,
          "openPct": -1.08,
          "buyRet": -5.82,
          "netRet": -6.01,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002166",
        "name": "莱茵生物",
        "industry": "化学制品",
        "price": 7.21,
        "gain": 4.95,
        "turnover": 3.91,
        "volRatio": 3.5,
        "cap": 53,
        "yang": 2,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -1.38,
          "hit": false,
          "price": 7.15,
          "code": "002166",
          "at": "2026-09-09",
          "open": 7.14,
          "openPct": -1.52,
          "buyRet": 0.14,
          "netRet": -0.06,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000525",
        "name": "红太阳",
        "industry": "农化制品",
        "price": 4.99,
        "gain": 4.61,
        "turnover": 3.86,
        "volRatio": 1.97,
        "cap": 65,
        "yang": 3,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": 0.6,
          "hit": true,
          "price": 5.06,
          "code": "000525",
          "at": "2026-09-09",
          "open": 5,
          "openPct": -0.6,
          "buyRet": 1.2,
          "netRet": 1,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603086",
        "name": "先达股份",
        "industry": "农化制品",
        "price": 6.53,
        "gain": 4.31,
        "turnover": 7.27,
        "volRatio": 1.26,
        "cap": 28,
        "yang": 2,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": -0.91,
          "hit": false,
          "price": 6.51,
          "code": "603086",
          "at": "2026-09-09",
          "open": 6.56,
          "openPct": -0.15,
          "buyRet": -0.76,
          "netRet": -0.96,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000713",
        "name": "国投丰乐",
        "industry": "种植业",
        "price": 7.08,
        "gain": 4.27,
        "turnover": 7.58,
        "volRatio": 1.15,
        "cap": 57,
        "yang": 3,
        "aboveRate": 98,
        "sector": "农业/种业",
        "verify": {
          "gain": 2.41,
          "hit": true,
          "price": 7.23,
          "code": "000713",
          "at": "2026-09-09",
          "open": 6.9,
          "openPct": -2.27,
          "buyRet": 4.78,
          "netRet": 4.57,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603212",
        "name": "赛伍技术",
        "industry": "光伏设备",
        "price": 11.63,
        "gain": 4.21,
        "turnover": 2.93,
        "volRatio": 2.25,
        "cap": 51,
        "yang": 2,
        "aboveRate": 95,
        "sector": "新能源/车",
        "verify": {
          "gain": -0.43,
          "hit": false,
          "price": 11.65,
          "code": "603212",
          "at": "2026-09-09",
          "open": 11.7,
          "openPct": 0,
          "buyRet": -0.43,
          "netRet": -0.63,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600866",
        "name": "星湖科技",
        "industry": "化学制品",
        "price": 4.6,
        "gain": 4.07,
        "turnover": 3.07,
        "volRatio": 2.35,
        "cap": 76,
        "yang": 2,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": -0.87,
          "hit": false,
          "price": 4.57,
          "code": "600866",
          "at": "2026-09-09",
          "open": 4.59,
          "openPct": -0.43,
          "buyRet": -0.44,
          "netRet": -0.63,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002652",
        "name": "扬子新材",
        "industry": "装修建材",
        "price": 4.58,
        "gain": 3.85,
        "turnover": 6.14,
        "volRatio": 2.13,
        "cap": 23,
        "yang": 2,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": 7.63,
          "hit": true,
          "price": 4.94,
          "code": "002652",
          "at": "2026-09-09",
          "open": 4.64,
          "openPct": 1.09,
          "buyRet": 6.47,
          "netRet": 6.25,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000153",
        "name": "丰原药业",
        "industry": "化学制药",
        "price": 6.51,
        "gain": 3.83,
        "turnover": 3.09,
        "volRatio": 1.56,
        "cap": 30,
        "yang": 2,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.84,
          "hit": false,
          "price": 6.41,
          "code": "000153",
          "at": "2026-09-09",
          "open": 6.44,
          "openPct": -1.38,
          "buyRet": -0.47,
          "netRet": -0.66,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002758",
        "name": "浙农股份",
        "industry": "综合Ⅱ",
        "price": 9.29,
        "gain": 3.8,
        "turnover": 3.09,
        "volRatio": 1.03,
        "cap": 48,
        "yang": 2,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -0.32,
          "hit": false,
          "price": 9.27,
          "code": "002758",
          "at": "2026-09-09",
          "open": 9.2,
          "openPct": -1.08,
          "buyRet": 0.76,
          "netRet": 0.56,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000019",
        "name": "深粮控股",
        "industry": "农产品加工",
        "price": 7.66,
        "gain": 3.79,
        "turnover": 8.26,
        "volRatio": 1.02,
        "cap": 88,
        "yang": 2,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": 10.01,
          "hit": true,
          "price": 8.46,
          "code": "000019",
          "at": "2026-09-09",
          "open": 7.5,
          "openPct": -2.47,
          "buyRet": 12.8,
          "netRet": 12.57,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603739",
        "name": "蔚蓝生物",
        "industry": "化学制品",
        "price": 13.53,
        "gain": 3.76,
        "turnover": 2.91,
        "volRatio": 1.72,
        "cap": 34,
        "yang": 2,
        "aboveRate": 98,
        "sector": "",
        "verify": {
          "gain": -1.62,
          "hit": false,
          "price": 13.37,
          "code": "603739",
          "at": "2026-09-09",
          "open": 13.36,
          "openPct": -1.69,
          "buyRet": 0.07,
          "netRet": -0.13,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600313",
        "name": "农发种业",
        "industry": "种植业",
        "price": 8.08,
        "gain": 3.59,
        "turnover": 14.64,
        "volRatio": 1.37,
        "cap": 94,
        "yang": 3,
        "aboveRate": 97,
        "sector": "农业/种业",
        "verify": {
          "gain": 5.15,
          "hit": true,
          "price": 8.37,
          "code": "600313",
          "at": "2026-09-09",
          "open": 7.8,
          "openPct": -2.01,
          "buyRet": 7.31,
          "netRet": 7.09,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "601615",
        "name": "明阳智能",
        "industry": "风电设备",
        "price": 9.67,
        "gain": 3.42,
        "turnover": 2.56,
        "volRatio": 1.02,
        "cap": 219,
        "yang": 2,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": -1.13,
          "hit": false,
          "price": 9.61,
          "code": "601615",
          "at": "2026-09-09",
          "open": 9.68,
          "openPct": -0.41,
          "buyRet": -0.72,
          "netRet": -0.92,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002582",
        "name": "好想你",
        "industry": "休闲食品",
        "price": 10.88,
        "gain": 3.42,
        "turnover": 10.59,
        "volRatio": 1.88,
        "cap": 49,
        "yang": 2,
        "aboveRate": 99,
        "sector": "消费",
        "verify": {
          "gain": -1.92,
          "hit": false,
          "price": 10.75,
          "code": "002582",
          "at": "2026-09-09",
          "open": 10.87,
          "openPct": -0.82,
          "buyRet": -1.1,
          "netRet": -1.3,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603970",
        "name": "中农立华",
        "industry": "农化制品",
        "price": 11.9,
        "gain": 3.21,
        "turnover": 2.91,
        "volRatio": 1.53,
        "cap": 32,
        "yang": 2,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": -0.92,
          "hit": false,
          "price": 11.79,
          "code": "603970",
          "at": "2026-09-09",
          "open": 11.87,
          "openPct": -0.25,
          "buyRet": -0.67,
          "netRet": -0.87,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002788",
        "name": "鹭燕医药",
        "industry": "医药商业",
        "price": 11.89,
        "gain": 3.03,
        "turnover": 5.58,
        "volRatio": 2.27,
        "cap": 46,
        "yang": 2,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -2.61,
          "hit": false,
          "price": 11.59,
          "code": "002788",
          "at": "2026-09-09",
          "open": 11.85,
          "openPct": -0.42,
          "buyRet": -2.19,
          "netRet": -2.39,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002679",
        "name": "福建金森",
        "industry": "林业Ⅱ",
        "price": 11.48,
        "gain": 2.78,
        "turnover": 10.87,
        "volRatio": 1.01,
        "cap": 27,
        "yang": 2,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": -0.87,
          "hit": false,
          "price": 11.37,
          "code": "002679",
          "at": "2026-09-09",
          "open": 11.13,
          "openPct": -2.96,
          "buyRet": 2.16,
          "netRet": 1.95,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002174",
        "name": "游族网络",
        "industry": "游戏Ⅱ",
        "price": 12.55,
        "gain": 2.7,
        "turnover": 3.3,
        "volRatio": 1.11,
        "cap": 123,
        "yang": 4,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.51,
          "hit": false,
          "price": 12.4,
          "code": "002174",
          "at": "2026-09-09",
          "open": 12.61,
          "openPct": 0.16,
          "buyRet": -1.67,
          "netRet": -1.86,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603458",
        "name": "勘设股份",
        "industry": "工程咨询服务Ⅱ",
        "price": 10.71,
        "gain": 2.59,
        "turnover": 5.1,
        "volRatio": 1.07,
        "cap": 33,
        "yang": 2,
        "aboveRate": 97,
        "sector": "",
        "verify": {
          "gain": 1.67,
          "hit": true,
          "price": 10.94,
          "code": "603458",
          "at": "2026-09-09",
          "open": 10.7,
          "openPct": -0.56,
          "buyRet": 2.24,
          "netRet": 2.04,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      }
    ]
  },
  {
    "date": "2026-09-07",
    "runAt": "2026-09-07 14:30",
    "count": 8,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "000417",
        "name": "合百集团",
        "industry": "一般零售",
        "price": 6.72,
        "gain": 6.67,
        "turnover": 11.7,
        "volRatio": 2.31,
        "cap": 52,
        "yang": 2,
        "aboveRate": 100,
        "sector": "消费",
        "verify": {
          "gain": -2.91,
          "hit": false,
          "price": 6.68,
          "code": "000417",
          "at": "2026-09-08",
          "open": 6.8,
          "openPct": -1.16,
          "buyRet": -1.76,
          "netRet": -1.96,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "603322",
        "name": "超讯科技",
        "industry": "通信服务",
        "price": 28.7,
        "gain": 5.67,
        "turnover": 5.07,
        "volRatio": 1.75,
        "cap": 45,
        "yang": 2,
        "aboveRate": 96,
        "sector": "算力/AI",
        "verify": {
          "gain": 2.78,
          "hit": true,
          "price": 29.56,
          "code": "603322",
          "at": "2026-09-08",
          "open": 28.99,
          "openPct": 0.8,
          "buyRet": 1.97,
          "netRet": 1.76,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000880",
        "name": "潍柴重机",
        "industry": "通用设备",
        "price": 25.51,
        "gain": 4.98,
        "turnover": 9.31,
        "volRatio": 2.07,
        "cap": 118,
        "yang": 3,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": -1.37,
          "hit": false,
          "price": 25.22,
          "code": "000880",
          "at": "2026-09-08",
          "open": 25.55,
          "openPct": -0.08,
          "buyRet": -1.29,
          "netRet": -1.49,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "003006",
        "name": "百亚股份",
        "industry": "个护用品",
        "price": 15.35,
        "gain": 4.71,
        "turnover": 2.81,
        "volRatio": 1.63,
        "cap": 66,
        "yang": 4,
        "aboveRate": 100,
        "sector": "",
        "verify": {
          "gain": 2.73,
          "hit": true,
          "price": 15.8,
          "code": "003006",
          "at": "2026-09-08",
          "open": 15.45,
          "openPct": 0.46,
          "buyRet": 2.27,
          "netRet": 2.06,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002985",
        "name": "北摩高科",
        "industry": "航空装备Ⅱ",
        "price": 28.97,
        "gain": 4.55,
        "turnover": 2.89,
        "volRatio": 2.25,
        "cap": 96,
        "yang": 3,
        "aboveRate": 100,
        "sector": "军工",
        "verify": {
          "gain": -0.34,
          "hit": false,
          "price": 29.08,
          "code": "002985",
          "at": "2026-09-08",
          "open": 29.18,
          "openPct": 0,
          "buyRet": -0.34,
          "netRet": -0.54,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "001360",
        "name": "南矿集团",
        "industry": "专用设备",
        "price": 19.31,
        "gain": 3.76,
        "turnover": 6.54,
        "volRatio": 1.45,
        "cap": 39,
        "yang": 3,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": 4.95,
          "hit": true,
          "price": 20.15,
          "code": "001360",
          "at": "2026-09-08",
          "open": 19.32,
          "openPct": 0.63,
          "buyRet": 4.3,
          "netRet": 4.09,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002251",
        "name": "步步高",
        "industry": "一般零售",
        "price": 3.94,
        "gain": 3.68,
        "turnover": 5.56,
        "volRatio": 1.19,
        "cap": 106,
        "yang": 2,
        "aboveRate": 99,
        "sector": "消费",
        "verify": {
          "gain": 3.31,
          "hit": true,
          "price": 4.06,
          "code": "002251",
          "at": "2026-09-08",
          "open": 3.94,
          "openPct": 0.25,
          "buyRet": 3.05,
          "netRet": 2.84,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000501",
        "name": "武商集团",
        "industry": "一般零售",
        "price": 7.75,
        "gain": 2.65,
        "turnover": 3.04,
        "volRatio": 1.74,
        "cap": 60,
        "yang": 2,
        "aboveRate": 100,
        "sector": "消费",
        "verify": {
          "gain": -0.77,
          "hit": false,
          "price": 7.72,
          "code": "000501",
          "at": "2026-09-08",
          "open": 7.75,
          "openPct": -0.39,
          "buyRet": -0.39,
          "netRet": -0.59,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      }
    ]
  },
  {
    "date": "2026-09-04",
    "runAt": "2026-09-04 14:30",
    "count": 7,
    "criteria": {
      "gain": "2.5%-7%",
      "turnover": "2.5%-20%",
      "cap": "20亿-500亿",
      "volRatio": ">1",
      "yang": "≥2连阳",
      "aboveAvg": "≥95% 时间在分时均线上",
      "exclude": "创业板/科创板/北交所/ST/退市"
    },
    "list": [
      {
        "code": "600689",
        "name": "上海三毛",
        "industry": "综合Ⅱ",
        "price": 12.57,
        "gain": 6.35,
        "turnover": 5.17,
        "volRatio": 1.05,
        "cap": 25,
        "yang": 3,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.26,
          "hit": false,
          "price": 12.5,
          "code": "600689",
          "at": "2026-09-07",
          "open": 12.66,
          "openPct": 0,
          "buyRet": -1.26,
          "netRet": -1.46,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "002438",
        "name": "江苏神通",
        "industry": "通用设备",
        "price": 14.57,
        "gain": 5.81,
        "turnover": 4.37,
        "volRatio": 6.26,
        "cap": 74,
        "yang": 2,
        "aboveRate": 96,
        "sector": "",
        "verify": {
          "gain": -2.89,
          "hit": false,
          "price": 14.11,
          "code": "002438",
          "at": "2026-09-07",
          "open": 14.58,
          "openPct": 0.34,
          "buyRet": -3.22,
          "netRet": -3.42,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600685",
        "name": "中船防务",
        "industry": "航海装备Ⅱ",
        "price": 27.64,
        "gain": 4.58,
        "turnover": 3.51,
        "volRatio": 2.88,
        "cap": 391,
        "yang": 3,
        "aboveRate": 100,
        "sector": "军工",
        "verify": {
          "gain": -0.69,
          "hit": false,
          "price": 27.25,
          "code": "600685",
          "at": "2026-09-07",
          "open": 27.33,
          "openPct": -0.4,
          "buyRet": -0.29,
          "netRet": -0.49,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "601118",
        "name": "海南橡胶",
        "industry": "种植业",
        "price": 7.05,
        "gain": 3.83,
        "turnover": 4.23,
        "volRatio": 1.34,
        "cap": 302,
        "yang": 3,
        "aboveRate": 98,
        "sector": "农业/种业",
        "verify": {
          "gain": 2.42,
          "hit": true,
          "price": 7.2,
          "code": "601118",
          "at": "2026-09-07",
          "open": 7.43,
          "openPct": 5.69,
          "buyRet": -3.1,
          "netRet": -3.29,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "600936",
        "name": "北投科技",
        "industry": "IT服务Ⅱ",
        "price": 5.47,
        "gain": 2.82,
        "turnover": 4.76,
        "volRatio": 1.33,
        "cap": 91,
        "yang": 4,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -1.47,
          "hit": false,
          "price": 5.37,
          "code": "600936",
          "at": "2026-09-07",
          "open": 5.59,
          "openPct": 2.57,
          "buyRet": -3.94,
          "netRet": -4.13,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "601890",
        "name": "亚星锚链",
        "industry": "航海装备Ⅱ",
        "price": 9.19,
        "gain": 2.8,
        "turnover": 4.73,
        "volRatio": 1.88,
        "cap": 88,
        "yang": 8,
        "aboveRate": 99,
        "sector": "军工",
        "verify": {
          "gain": -0.44,
          "hit": false,
          "price": 9.11,
          "code": "601890",
          "at": "2026-09-07",
          "open": 9.15,
          "openPct": 0,
          "buyRet": -0.44,
          "netRet": -0.64,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      },
      {
        "code": "000582",
        "name": "北部湾港",
        "industry": "航运港口",
        "price": 12.11,
        "gain": 2.63,
        "turnover": 2.84,
        "volRatio": 1.69,
        "cap": 305,
        "yang": 8,
        "aboveRate": 99,
        "sector": "",
        "verify": {
          "gain": -0.82,
          "hit": false,
          "price": 12.08,
          "code": "000582",
          "at": "2026-09-07",
          "open": 12.36,
          "openPct": 1.48,
          "buyRet": -2.27,
          "netRet": -2.46,
          "locked": false,
          "basis": "open-to-close",
          "by": "hist"
        }
      }
    ]
  }
];
